# Generated by Django 5.0.1 on 2024-02-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_date_created_course_date_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
