# Generated by Django 5.0.1 on 2024-02-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imuser',
            name='user_type',
            field=models.CharField(choices=[('EIT', 'Entrepreneur-In-Training'), ('TEACHING_FELLOW', 'Teaching Fellow'), ('ADMIN_STAFF', 'Administrative Staff'), ('ADMIN', 'Administrator')], default='EIT', max_length=20),
        ),
    ]
